---
title: "Traffic Accidents at Millbrae Redlight Cameras"
output: html_notebook
---



```{r}


# READ IN KAGGLE CLEANED DATASET - WELL-DOCUMENTED ASSUMPTIONS HERE:
# https://alexgude.com/blog/switrs-sqlite-hosted-dataset/

# Loading requisite libraries
library("RSQLite")
library(dplyr)
library(ggplot2)


setwd("C:/Users/robsc/OneDrive/Desktop/Old Desktop/Job App Docs/Traffic Camera Analysis/switrs_raw_csvs/")

cleandata <- dbConnect(RSQLite::SQLite(), "switrs.sqlite")


tables <- dbListTables(cleandata)


# Get tables from database and save as sep dataframes
lDataFrames <- vector("list", length = length(tables))

for (i in seq_along(tables)) {
    lDataFrames[[i]] <- dbGetQuery(conn = cleandata, statement = paste("SELECT * FROM '", tables[[i]], "'", sep = ""))
}

# Saving as four sep datasets
df1 <- lDataFrames[[1]] # Case ID and year
df2 <- lDataFrames[[2]] # Case ID and collisions
df3 <- lDataFrames[[3]] # Case ID and parties
df4 <- lDataFrames[[4]] # Case ID and victims


# Combining ind datasets - only need case ID, year, and collision data
# 9,424,334 observations w/ 76 variables
cleanswitrs <- merge(df1, df2, by = "case_id")

# Remove extraneous datasets to spare memory
rm(cleandata, df1, df2, df3, df4)

# Preliminary set of data:
# collision_date, (latitude, longitude), type_of_collision, collision_severity, caltrans_district
# caltrans_county, primary_road, secondary_road, intersection, db_year, case_id
cleanswitrssubset <- cleanswitrs[c("collision_date", "latitude", "longitude", "type_of_collision","collision_severity","caltrans_district","caltrans_county","primary_road","secondary_road","intersection","db_year","case_id")]

# Restrict to years of interest

cleanswitrssubset$collision_date <- as.Date(cleanswitrssubset$collision_date)

cleanswitrssubsetyears <- filter(cleanswitrssubset, cleanswitrssubset$collision_date >= "2004-01-01" & cleanswitrssubset$collision_date <= "2013-12-31")
# Now 4,550,457 observations and 12 variables


###########
# Restrict to the correct roads
###########

# Millbrae Av as primary or secondary
# Will be close to comprehensive given all cameras intersect w/ Millbrae Av
millbraeav <- filter(cleanswitrssubsetyears, cleanswitrssubsetyears$primary_road == "MILLBRAE AV" | cleanswitrssubsetyears$secondary_road == "MILLBRAE AV")
# 1022 observations


# Rollins as primary or secondary road
rollinsrd <- filter(cleanswitrssubsetyears, cleanswitrssubsetyears$primary_road == "ROLLINS RD" | cleanswitrssubsetyears$secondary_road == "ROLLINS RD")
# 423 observations

# El Camino as primary or secondary road (far broader than we need)
elcam <- filter(cleanswitrssubsetyears, cleanswitrssubsetyears$primary_road == "EL CAMINO REAL" | cleanswitrssubsetyears$secondary_road == "EL CAMINO REAL")
# 12,431 observations

# RT 101 as primary or secondary road (far broader than we need)
RT101 <- filter(cleanswitrssubsetyears, cleanswitrssubsetyears$primary_road == "RT 101" | cleanswitrssubsetyears$secondary_road == "RT 101")
# 162,445 observations


#########
# Creating intersection-specific datasets
#########

# Restricting to Rollins AND Millbrae
rollinsnmillbrae <- filter(rollinsrd, rollinsrd$primary_road == "MILLBRAE AV" | rollinsrd$secondary_road == "MILLBRAE AV")
# 41 observations

rollinsnmillbrae$accident <- 1

rollinsnmillbrae2 <- filter(millbraeav, millbraeav$primary_road == "ROLLINS RD" | millbraeav$secondary_road == "ROLLINS RD")
# Also 41 observations - encouraging


# Intersection of Millbrae and El Camino
elcamnmillbrae <- filter(millbraeav, millbraeav$primary_road == "EL CAMINO REAL" | millbraeav$secondary_road == "EL CAMINO REAL")
# 42 observations


# Intersection of Millbrae and Rt 101 (either SB or NB for now...)
RT101nmillbrae <- filter(millbraeav, millbraeav$primary_road == "RT 101" | millbraeav$secondary_road == "RT 101")
# 686 observations


##########
# Basic plots of data
##########


# FIRST just count and plot all of these - then limit to those w/ 1 for intersection
elcamnmillbrae$accident <- 1

# Sum accidents by year and plot (then by month-year)
elcamnmillbrae$year <- format(as.Date(elcamnmillbrae$collision_date, format="%d/%m/%Y"),"%Y")

# Create accident-year dataset
elcamnmillbraeag <- aggregate(elcamnmillbrae$accident, list(elcamnmillbrae$collision_date), FUN=sum) 
elcamnmillbraeag$Group.1 <- as.Date(elcamnmillbraeag$Group.1)

# Now grouping by month to plot
elcammilldat <- elcamnmillbraeag %>%
  group_by(month = lubridate::floor_date(Group.1, 'month')) %>%
  summarize(sum = sum(x))


ggplot(data = elcammilldat, aes(x = month, y = sum)) + geom_line()
# Almost nonexistent accidents and spike is post-cameras...




# Creating indicator for accident and year, month/year variables
millbraeav$accident <- 1
millbraeav$year <- format(as.Date(millbraeav$collision_date, format="%d/%m/%Y"),"%Y")
millbraeav$yearmo <- format(as.Date(millbraeav$collision_date, format="%d/%m/%Y"),"%m/%y")


# TESTING OUT ACROSS ALL OF MILLBRAE AV - Being charitable
# Create accident-year dataset
millbraeag <- aggregate(millbraeav$accident, list(millbraeav$collision_date), FUN=sum) 
millbraeag$Group.1 <- as.Date(millbraeag$Group.1)

# Now grouping by month to plot
newdata <- millbraeag %>%
  group_by(month = lubridate::floor_date(Group.1, 'month')) %>%
  summarize(sum = sum(x))


ggplot(data = newdata, aes(x = month, y = sum)) + geom_line() + geom_vline(xintercept=as.Date("2006-09-01"), linetype="dotted")
# Accidents fell to low right BEFORE cameras were installed and then began to rise once more
# Likely useful to introduce smoothing here - maybe over 2 months?

```


## Creating the same dataset but without restricting upper bound

```{r}



# Restrict from 2004 on...
cleanswitrssubsetyears04on <- filter(cleanswitrssubset, cleanswitrssubset$collision_date >= "2004-01-01")
# Now 7,818,077 observations and 12 variables


###########
# Restrict to the correct roads
###########

# Millbrae Av as primary or secondary
# Will be close to comprehensive given all cameras intersect w/ Millbrae Av
millbraeav <- filter(cleanswitrssubsetyears04on, cleanswitrssubsetyears04on$primary_road == "MILLBRAE AV" | cleanswitrssubsetyears04on$secondary_road == "MILLBRAE AV")
# 1022 observations


# Rollins as primary or secondary road
rollinsrd <- filter(cleanswitrssubsetyears04on, cleanswitrssubsetyears04on$primary_road == "ROLLINS RD" | cleanswitrssubsetyears04on$secondary_road == "ROLLINS RD")
# 423 observations

# El Camino as primary or secondary road (far broader than we need)
elcam <- filter(cleanswitrssubsetyears04on, cleanswitrssubsetyears04on$primary_road == "EL CAMINO REAL" | cleanswitrssubsetyears04on$secondary_road == "EL CAMINO REAL")
# 12,431 observations

# RT 101 as primary or secondary road (far broader than we need)
RT101 <- filter(cleanswitrssubsetyears04on, cleanswitrssubsetyears04on$primary_road == "RT 101" | cleanswitrssubsetyears04on$secondary_road == "RT 101")
# 162,445 observations


#########
# Creating intersection-specific datasets
#########

# Restricting to Rollins AND Millbrae
rollinsnmillbrae <- filter(rollinsrd, rollinsrd$primary_road == "MILLBRAE AV" | rollinsrd$secondary_road == "MILLBRAE AV")
# 41 observations

rollinsnmillbrae$accident <- 1

rollinsnmillbrae2 <- filter(millbraeav, millbraeav$primary_road == "ROLLINS RD" | millbraeav$secondary_road == "ROLLINS RD")
# Also 41 observations - encouraging


# Intersection of Millbrae and El Camino
elcamnmillbrae <- filter(millbraeav, millbraeav$primary_road == "EL CAMINO REAL" | millbraeav$secondary_road == "EL CAMINO REAL")
# 42 observations


# Intersection of Millbrae and Rt 101 (either SB or NB for now...)
RT101nmillbrae <- filter(millbraeav, millbraeav$primary_road == "RT 101" | millbraeav$secondary_road == "RT 101")
# 686 observations


##########
# Basic plots of data
##########


# FIRST just count and plot all of these - then limit to those w/ 1 for intersection
elcamnmillbrae$accident <- 1

# Sum accidents by year and plot (then by month-year)
elcamnmillbrae$year <- format(as.Date(elcamnmillbrae$collision_date, format="%d/%m/%Y"),"%Y")

# Create accident-year dataset
elcamnmillbraeag <- aggregate(elcamnmillbrae$accident, list(elcamnmillbrae$collision_date), FUN=sum) 
elcamnmillbraeag$Group.1 <- as.Date(elcamnmillbraeag$Group.1)

# Now grouping by month to plot
elcammilldat <- elcamnmillbraeag %>%
  group_by(month = lubridate::floor_date(Group.1, 'month')) %>%
  summarize(sum = sum(x))


ggplot(data = elcammilldat, aes(x = month, y = sum)) + geom_line()
# Almost nonexistent accidents and spike is post-cameras...




# Creating indicator for accident and year, month/year variables
millbraeav$accident <- 1
millbraeav$year <- format(as.Date(millbraeav$collision_date, format="%d/%m/%Y"),"%Y")
millbraeav$yearmo <- format(as.Date(millbraeav$collision_date, format="%d/%m/%Y"),"%m/%y")


# TESTING OUT ACROSS ALL OF MILLBRAE AV - Being charitable
# Create accident-year dataset
millbraeag <- aggregate(millbraeav$accident, list(millbraeav$collision_date), FUN=sum) 
millbraeag$Group.1 <- as.Date(millbraeag$Group.1)

# Now grouping by month to plot
newdata <- millbraeag %>%
  group_by(month = lubridate::floor_date(Group.1, 'month')) %>%
  summarize(sum = sum(x))


ggplot(data = newdata, aes(x = month, y = sum)) + geom_line() + geom_vline(xintercept=as.Date("2006-09-01"), linetype="dotted")
# Accidents fell to low right BEFORE cameras were installed and then began to rise once more
# Likely useful to introduce smoothing here - maybe over 2 months?

```



## RAW DATA CLEANING CHECKS (NOT USED CURRENTLY)

```{r}

# RAW DATA PROCESSING...

library(dplyr)


# FROM https://www.kaggle.com/datasets/alexgude/california-traffic-collision-raw-switrs-data?resource=download
# Seems delimiters vary by year...


# Reading in all available collision records - covers 2001 to 2020

# First dataset
data1 <- read.csv("C:/Users/robsc/OneDrive/Desktop/Old Desktop/Job App Docs/Traffic Camera Analysis/switrs_raw_csvs/20160924/20160924_CollisionRecords.txt")

# Second dataset
data2 <- read.csv("C:/Users/robsc/OneDrive/Desktop/Old Desktop/Job App Docs/Traffic Camera Analysis/switrs_raw_csvs/20170112/20170112_CollisionRecords.txt")

# Third dataset
data3 <- read.csv("C:/Users/robsc/OneDrive/Desktop/Old Desktop/Job App Docs/Traffic Camera Analysis/switrs_raw_csvs/20180925/20180925_CollisionRecords.txt")
# Produced warning - EOF within quoted string...

# Fourth dataset
data4 <- read.csv("C:/Users/robsc/OneDrive/Desktop/Old Desktop/Job App Docs/Traffic Camera Analysis/switrs_raw_csvs/20201024/20201024_CollisionRecords.txt")

# Fifth dataset
data5 <- read.csv("C:/Users/robsc/OneDrive/Desktop/Old Desktop/Job App Docs/Traffic Camera Analysis/switrs_raw_csvs/20210604/CollisionRecords.txt")



# Convert to a data frame
data1 <- as.data.frame(data1)
data2 <- as.data.frame(data2)
data3 <- as.data.frame(data3)
data4 <- as.data.frame(data4)
data5 <- as.data.frame(data5)


# Restrict to district 8
dist8data1 <- filter(data1, data1$CALTRANS_DISTRICT == "8")
# 150,235 observations w/ 76 variables

dist8data2 <- filter(data2, data2$CALTRANS_DISTRICT == "8")
# 150,238 observations w/ 76 variables

dist8data3 <- filter(data3, data3$CALTRANS_DISTRICT == "8")
# 152,408 observations w/ 76 variables

dist8data4 <- filter(data4, data4$CALTRANS_DISTRICT == "8")
# 24,677 observations w/ 76 variables

dist8data5 <- filter(data5, data5$CALTRANS_DISTRICT == "8")
# 7,501 observations w/ 76 variables


######
# Accident years from 2004 to 2013 (2012 and 2013 for cross-validation w/ SWITRS)
######

# Dataset 1
dist8datayears1 <- filter(dist8data1, as.numeric(dist8data1$ACCIDENT_YEAR) >= 2004 & as.numeric(dist8data1$ACCIDENT_YEAR) <= 2013)

# Dataset 2
dist8datayears2 <- filter(dist8data2, as.numeric(dist8data2$ACCIDENT_YEAR) >= 2004 & as.numeric(dist8data2$ACCIDENT_YEAR) <= 2013)

# Dataset 3
dist8datayears3 <- filter(dist8data3, as.numeric(dist8data3$ACCIDENT_YEAR) >= 2004 & as.numeric(dist8data3$ACCIDENT_YEAR) <= 2013)

# Dataset 4
dist8datayears4 <- filter(dist8data4, as.numeric(dist8data4$ACCIDENT_YEAR) >= 2004 & as.numeric(dist8data4$ACCIDENT_YEAR) <= 2013)

# Dataset 5
dist8datayears5 <- filter(dist8data5, as.numeric(dist8data5$ACCIDENT_YEAR) >= 2004 & as.numeric(dist8data5$ACCIDENT_YEAR) <= 2013)


# Remove precursor datasets
rm(data1, data2, data3, data4, data5, dist8data1, dist8data2, dist8data3, dist8data4, dist8data5)


# Merging 5 datasets
mergeddata <- rbind(dist8datayears1, dist8datayears2, dist8datayears3, dist8datayears4, dist8datayears5)
# 314,673 observations w/ 76 variables

# Restrict to unique rows
mergeddatanodups <- mergeddata %>% distinct()
# Drops from 314,673 observations to 119,947
# Will likely want to filter by case ID later

roads <- unique(mergeddatanodups$PRIMARY_RD)


# Restrict to roads of interest
millbraeavdata <- filter(mergeddatanodups, mergeddatanodups$PRIMARY_RD == "MILLBRAE AV")
rollinsrddata <- filter(mergeddatanodups, mergeddatanodups$PRIMARY_RD == "ROLLINS RD")

```

